### PR TITLE
Commit 3

### PR DESCRIPTION
**Pull request by manasworks**
Hey guys please check it

### CODE REVIEW

**Review by omer21349 — COMMENTED** [review]
good

**Review by elvirka7 — APPROVED** [review]
Thank you!!!

**Review by omer21349 — APPROVED** [review]
good

**Review by KseniiaKr — APPROVED** [review]
done

**Review by omer21349 — APPROVED** [review]

**Review by omer21349 — APPROVED** [review]

**Review by Muratbey33 — APPROVED** [review]
looks good

**Review by KseniiaKr — APPROVED** [review]
good

**Pull request merged**
